// Generated by npm run build. Edit src/setup/ instead.
// Includes jsonc-parser (MIT); see THIRD-PARTY-NOTICES.txt.

// src/setup/cli.mjs
import { parseArgs } from "node:util";
import { pathToFileURL } from "node:url";

// src/setup/setup.mjs
import { homedir } from "node:os";
import { realpath } from "node:fs/promises";
import path2 from "node:path";

// src/setup/kiro.mjs
import { execFile } from "node:child_process";
import { createHash as createHash2 } from "node:crypto";
import { readFile } from "node:fs/promises";
import { createServer } from "node:net";
import { promisify } from "node:util";

// src/setup/errors.mjs
var SetupError = class extends Error {
  constructor(code, message) {
    super(message);
    this.name = "SetupError";
    this.code = code;
  }
};
function fail(code, message) {
  throw new SetupError(code, message);
}
function isObject(value) {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

// src/setup/discovery.mjs
import { createHash } from "node:crypto";
var MAX_RESPONSE_BYTES = 128 * 1024;
var SCOPES = ["workflow:read", "workflow:write", "workflow:execute", "execution:read"];
function safeUrl(value, origin) {
  let url;
  try {
    url = new URL(value);
  } catch {
    fail("INVALID_URL", "Use an absolute n8n instance or MCP URL.");
  }
  const loopback = ["localhost", "127.0.0.1", "[::1]"].includes(url.hostname);
  if (url.protocol !== "https:" && !(url.protocol === "http:" && loopback) || url.username || url.password || url.search || url.hash) {
    fail("INVALID_URL", "Use HTTPS (HTTP is allowed on loopback), without credentials, query parameters or fragments.");
  }
  if (origin && url.origin !== origin) {
    fail("UNSUPPORTED_ISSUER", "This helper supports OAuth metadata and endpoints on the same origin as n8n.");
  }
  return url;
}
function normalizeEndpoint(value) {
  const url = safeUrl(value);
  const base = url.pathname.replace(/\/+$/, "");
  url.pathname = base.endsWith("/mcp-server/http") ? base : `${base}/mcp-server/http`;
  return url.href;
}
function defaultName(endpoint) {
  const host = new URL(endpoint).hostname.replace(/[^a-zA-Z0-9-]/g, "-").slice(0, 40);
  const suffix = createHash("sha256").update(endpoint).digest("hex").slice(0, 10);
  return `n8n-${host}-${suffix}`;
}
async function request(url, { method = "GET", body, timeout = 1e4, fetchImpl = fetch, probe = false } = {}) {
  try {
    const response = await fetchImpl(url, {
      method,
      redirect: "manual",
      signal: AbortSignal.timeout(timeout),
      headers: { Accept: "application/json", ...body ? { "Content-Type": "application/json" } : {} },
      ...body ? { body: JSON.stringify(body) } : {}
    });
    const status = response.status;
    const challenge = response.headers.get("www-authenticate");
    if (status >= 300 && status < 400) {
      await response.body?.cancel();
      fail("REDIRECT", "The server redirected the request. Use its final n8n URL; login-proxy redirects are unsupported.");
    }
    if (probe) {
      await response.body?.cancel();
      return { status, challenge };
    }
    const reader = response.body?.getReader();
    const chunks = [];
    let size = 0;
    if (reader) {
      while (true) {
        const part = await reader.read();
        if (part.done) break;
        size += part.value.length;
        if (size > MAX_RESPONSE_BYTES) {
          await reader.cancel();
          fail("INVALID_RESPONSE", "The server response exceeded the metadata size limit.");
        }
        chunks.push(part.value);
      }
    }
    let data;
    try {
      data = JSON.parse(Buffer.concat(chunks).toString("utf8"));
    } catch {
      fail("INVALID_RESPONSE", `Expected JSON from n8n (HTTP ${status}). Check the URL, MCP setting and reverse proxy.`);
    }
    if (!isObject(data)) fail("INVALID_RESPONSE", "Expected a JSON metadata object from n8n.");
    return { status, data };
  } catch (error) {
    if (error instanceof SetupError) throw error;
    fail("NETWORK", "The n8n request failed or timed out. Check connectivity and the configured URL.");
  }
}
async function discover(endpoint, options = {}) {
  const resourceUrl = safeUrl(endpoint);
  const probe = await request(endpoint, { ...options, probe: true });
  const match = probe.challenge?.match(/\bresource_metadata\s*=\s*"([^"\r\n]+)"/i);
  if (probe.status !== 401 || !match) {
    fail("DISCOVERY", `Expected an OAuth resource-metadata challenge (HTTP ${probe.status}). Check the MCP endpoint, instance setting and proxy.`);
  }
  const metadataUrl = safeUrl(match[1], resourceUrl.origin);
  const resource = await request(metadataUrl.href, options);
  if (resource.status !== 200 || resource.data.resource !== endpoint || !Array.isArray(resource.data.authorization_servers) || resource.data.authorization_servers.length !== 1) {
    fail("DISCOVERY", "Resource metadata must match this MCP endpoint and advertise one authorization server.");
  }
  const issuer = resource.data.authorization_servers[0];
  const issuerUrl = safeUrl(issuer, resourceUrl.origin);
  const path3 = issuerUrl.pathname === "/" ? "" : issuerUrl.pathname;
  const metadata = await request(`${issuerUrl.origin}/.well-known/oauth-authorization-server${path3}`, options);
  if (metadata.status !== 200 || metadata.data.issuer !== issuer) {
    fail("ISSUER_MISMATCH", "OAuth discovery must return an issuer identical to the advertised authorization server.");
  }
  const data = metadata.data;
  for (const key of ["authorization_endpoint", "token_endpoint", "registration_endpoint"]) safeUrl(data[key], resourceUrl.origin);
  for (const [key, required] of Object.entries({
    token_endpoint_auth_methods_supported: ["none"],
    code_challenge_methods_supported: ["S256"],
    response_types_supported: ["code"],
    grant_types_supported: ["authorization_code", "refresh_token"]
  })) {
    if (!Array.isArray(data[key]) || required.some((value) => !data[key].includes(value))) {
      fail("UNSUPPORTED_OAUTH", "This server must advertise public clients, S256 PKCE, authorization codes and refresh tokens.");
    }
  }
  return { issuer, registrationEndpoint: data.registration_endpoint };
}
async function register(discovery, callbackUri2, options = {}) {
  const body = {
    client_name: "n8n for Kiro",
    redirect_uris: [callbackUri2],
    token_endpoint_auth_method: "none",
    grant_types: ["authorization_code", "refresh_token"],
    response_types: ["code"]
  };
  let result;
  try {
    result = await request(discovery.registrationEndpoint, { ...options, method: "POST", body });
  } catch {
    fail("REGISTRATION_UNCERTAIN", "Registration may have reached n8n, but no valid response was received. Do not retry automatically; consult the instance administrator and use repair --new-registration to explicitly retry.");
  }
  if (result.status !== 201) {
    fail("REGISTRATION_REJECTED", `n8n rejected public-client registration (HTTP ${result.status}). Check callback policy and registered-client limits with the administrator.`);
  }
  const data = result.data;
  if (typeof data.client_id !== "string" || !data.client_id || data.client_id.length > 2048 || /[\x00-\x1f\x7f]/.test(data.client_id) || "client_secret" in data || data.token_endpoint_auth_method !== "none" || !Array.isArray(data.redirect_uris) || data.redirect_uris.length !== 1 || data.redirect_uris[0] !== callbackUri2 || !Array.isArray(data.grant_types) || !body.grant_types.every((value) => data.grant_types.includes(value)) || !Array.isArray(data.response_types) || !data.response_types.includes("code")) {
    fail("REGISTRATION_UNCERTAIN", "n8n returned an unexpected registration. It was not installed. Consult the instance administrator before repair --new-registration.");
  }
  return data.client_id;
}

// src/setup/kiro.mjs
async function detectKiroVersion() {
  if (process.platform === "darwin") {
    try {
      const product = JSON.parse(await readFile("/Applications/Kiro.app/Contents/Resources/app/product.json", "utf8"));
      if (product.applicationName === "kiro") return product.version;
    } catch {
    }
  }
  try {
    const { stdout } = await promisify(execFile)("kiro", ["--version"], { timeout: 1e4, maxBuffer: 4096, windowsHide: true });
    return stdout.match(/^\d+\.\d+\.\d+$/m)?.[0];
  } catch {
    return void 0;
  }
}
function requireSupportedKiro(version) {
  if (version !== "1.1.70") {
    fail("KIRO_VERSION", "The current helper is validated for Kiro IDE 1.1.70 only. Check Help > About; supply --kiro-version 1.1.70 only if that is the installed version.");
  }
}
async function availablePort(port = 0) {
  if (!Number.isInteger(port) || port !== 0 && (port < 1024 || port > 65535)) {
    fail("CALLBACK_PORT", "Choose a callback port between 1024 and 65535.");
  }
  return await new Promise((resolve, reject) => {
    const server = createServer();
    server.once("error", () => reject(Object.assign(new Error("Callback port is unavailable. Choose another --callback-port."), { code: "CALLBACK_PORT" })));
    server.listen(port, "localhost", () => {
      const selected = server.address().port;
      server.close((error) => error ? reject(error) : resolve(selected));
    });
  });
}
function callbackUri(port) {
  return `http://localhost:${port}/oauth/callback`;
}
function connectionConfig(endpoint, clientId, port) {
  return {
    url: endpoint,
    timeout: 3e5,
    // Kiro 1.1.70 keys credentials by URL + headers, ignoring oauth.clientId.
    // A public identifier isolates grants after repair and from other clients.
    headers: { "X-N8N-Kiro-Connection": createHash2("sha256").update(clientId).digest("hex") },
    oauth: { clientId, redirectUri: `localhost:${port}` },
    // 1.1.70 accepts this field but may request all advertised scopes. Consent remains authoritative.
    oauthScopes: SCOPES
  };
}

// src/setup/storage.mjs
import { createHash as createHash3, randomUUID } from "node:crypto";
import { lstat, mkdir, open, readFile as readFile2, rename, rm } from "node:fs/promises";
import path from "node:path";

// node_modules/jsonc-parser/lib/esm/impl/scanner.js
function createScanner(text, ignoreTrivia = false) {
  const len = text.length;
  let pos = 0, value = "", tokenOffset = 0, token = 16, lineNumber = 0, lineStartOffset = 0, tokenLineStartOffset = 0, prevTokenLineStartOffset = 0, scanError = 0;
  function scanHexDigits(count, exact) {
    let digits = 0;
    let value2 = 0;
    while (digits < count || !exact) {
      let ch = text.charCodeAt(pos);
      if (ch >= 48 && ch <= 57) {
        value2 = value2 * 16 + ch - 48;
      } else if (ch >= 65 && ch <= 70) {
        value2 = value2 * 16 + ch - 65 + 10;
      } else if (ch >= 97 && ch <= 102) {
        value2 = value2 * 16 + ch - 97 + 10;
      } else {
        break;
      }
      pos++;
      digits++;
    }
    if (digits < count) {
      value2 = -1;
    }
    return value2;
  }
  function setPosition(newPosition) {
    pos = newPosition;
    value = "";
    tokenOffset = 0;
    token = 16;
    scanError = 0;
  }
  function scanNumber() {
    let start = pos;
    if (text.charCodeAt(pos) === 48) {
      pos++;
    } else {
      pos++;
      while (pos < text.length && isDigit(text.charCodeAt(pos))) {
        pos++;
      }
    }
    if (pos < text.length && text.charCodeAt(pos) === 46) {
      pos++;
      if (pos < text.length && isDigit(text.charCodeAt(pos))) {
        pos++;
        while (pos < text.length && isDigit(text.charCodeAt(pos))) {
          pos++;
        }
      } else {
        scanError = 3;
        return text.substring(start, pos);
      }
    }
    let end = pos;
    if (pos < text.length && (text.charCodeAt(pos) === 69 || text.charCodeAt(pos) === 101)) {
      pos++;
      if (pos < text.length && text.charCodeAt(pos) === 43 || text.charCodeAt(pos) === 45) {
        pos++;
      }
      if (pos < text.length && isDigit(text.charCodeAt(pos))) {
        pos++;
        while (pos < text.length && isDigit(text.charCodeAt(pos))) {
          pos++;
        }
        end = pos;
      } else {
        scanError = 3;
      }
    }
    return text.substring(start, end);
  }
  function scanString() {
    let result = "", start = pos;
    while (true) {
      if (pos >= len) {
        result += text.substring(start, pos);
        scanError = 2;
        break;
      }
      const ch = text.charCodeAt(pos);
      if (ch === 34) {
        result += text.substring(start, pos);
        pos++;
        break;
      }
      if (ch === 92) {
        result += text.substring(start, pos);
        pos++;
        if (pos >= len) {
          scanError = 2;
          break;
        }
        const ch2 = text.charCodeAt(pos++);
        switch (ch2) {
          case 34:
            result += '"';
            break;
          case 92:
            result += "\\";
            break;
          case 47:
            result += "/";
            break;
          case 98:
            result += "\b";
            break;
          case 102:
            result += "\f";
            break;
          case 110:
            result += "\n";
            break;
          case 114:
            result += "\r";
            break;
          case 116:
            result += "	";
            break;
          case 117:
            const ch3 = scanHexDigits(4, true);
            if (ch3 >= 0) {
              result += String.fromCharCode(ch3);
            } else {
              scanError = 4;
            }
            break;
          default:
            scanError = 5;
        }
        start = pos;
        continue;
      }
      if (ch >= 0 && ch <= 31) {
        if (isLineBreak(ch)) {
          result += text.substring(start, pos);
          scanError = 2;
          break;
        } else {
          scanError = 6;
        }
      }
      pos++;
    }
    return result;
  }
  function scanNext() {
    value = "";
    scanError = 0;
    tokenOffset = pos;
    lineStartOffset = lineNumber;
    prevTokenLineStartOffset = tokenLineStartOffset;
    if (pos >= len) {
      tokenOffset = len;
      return token = 17;
    }
    let code = text.charCodeAt(pos);
    if (isWhiteSpace(code)) {
      do {
        pos++;
        value += String.fromCharCode(code);
        code = text.charCodeAt(pos);
      } while (isWhiteSpace(code));
      return token = 15;
    }
    if (isLineBreak(code)) {
      pos++;
      value += String.fromCharCode(code);
      if (code === 13 && text.charCodeAt(pos) === 10) {
        pos++;
        value += "\n";
      }
      lineNumber++;
      tokenLineStartOffset = pos;
      return token = 14;
    }
    switch (code) {
      // tokens: []{}:,
      case 123:
        pos++;
        return token = 1;
      case 125:
        pos++;
        return token = 2;
      case 91:
        pos++;
        return token = 3;
      case 93:
        pos++;
        return token = 4;
      case 58:
        pos++;
        return token = 6;
      case 44:
        pos++;
        return token = 5;
      // strings
      case 34:
        pos++;
        value = scanString();
        return token = 10;
      // comments
      case 47:
        const start = pos - 1;
        if (text.charCodeAt(pos + 1) === 47) {
          pos += 2;
          while (pos < len) {
            if (isLineBreak(text.charCodeAt(pos))) {
              break;
            }
            pos++;
          }
          value = text.substring(start, pos);
          return token = 12;
        }
        if (text.charCodeAt(pos + 1) === 42) {
          pos += 2;
          const safeLength = len - 1;
          let commentClosed = false;
          while (pos < safeLength) {
            const ch = text.charCodeAt(pos);
            if (ch === 42 && text.charCodeAt(pos + 1) === 47) {
              pos += 2;
              commentClosed = true;
              break;
            }
            pos++;
            if (isLineBreak(ch)) {
              if (ch === 13 && text.charCodeAt(pos) === 10) {
                pos++;
              }
              lineNumber++;
              tokenLineStartOffset = pos;
            }
          }
          if (!commentClosed) {
            pos++;
            scanError = 1;
          }
          value = text.substring(start, pos);
          return token = 13;
        }
        value += String.fromCharCode(code);
        pos++;
        return token = 16;
      // numbers
      case 45:
        value += String.fromCharCode(code);
        pos++;
        if (pos === len || !isDigit(text.charCodeAt(pos))) {
          return token = 16;
        }
      // found a minus, followed by a number so
      // we fall through to proceed with scanning
      // numbers
      case 48:
      case 49:
      case 50:
      case 51:
      case 52:
      case 53:
      case 54:
      case 55:
      case 56:
      case 57:
        value += scanNumber();
        return token = 11;
      // literals and unknown symbols
      default:
        while (pos < len && isUnknownContentCharacter(code)) {
          pos++;
          code = text.charCodeAt(pos);
        }
        if (tokenOffset !== pos) {
          value = text.substring(tokenOffset, pos);
          switch (value) {
            case "true":
              return token = 8;
            case "false":
              return token = 9;
            case "null":
              return token = 7;
          }
          return token = 16;
        }
        value += String.fromCharCode(code);
        pos++;
        return token = 16;
    }
  }
  function isUnknownContentCharacter(code) {
    if (isWhiteSpace(code) || isLineBreak(code)) {
      return false;
    }
    switch (code) {
      case 125:
      case 93:
      case 123:
      case 91:
      case 34:
      case 58:
      case 44:
      case 47:
        return false;
    }
    return true;
  }
  function scanNextNonTrivia() {
    let result;
    do {
      result = scanNext();
    } while (result >= 12 && result <= 15);
    return result;
  }
  return {
    setPosition,
    getPosition: () => pos,
    scan: ignoreTrivia ? scanNextNonTrivia : scanNext,
    getToken: () => token,
    getTokenValue: () => value,
    getTokenOffset: () => tokenOffset,
    getTokenLength: () => pos - tokenOffset,
    getTokenStartLine: () => lineStartOffset,
    getTokenStartCharacter: () => tokenOffset - prevTokenLineStartOffset,
    getTokenError: () => scanError
  };
}
function isWhiteSpace(ch) {
  return ch === 32 || ch === 9;
}
function isLineBreak(ch) {
  return ch === 10 || ch === 13;
}
function isDigit(ch) {
  return ch >= 48 && ch <= 57;
}
var CharacterCodes;
(function(CharacterCodes2) {
  CharacterCodes2[CharacterCodes2["lineFeed"] = 10] = "lineFeed";
  CharacterCodes2[CharacterCodes2["carriageReturn"] = 13] = "carriageReturn";
  CharacterCodes2[CharacterCodes2["space"] = 32] = "space";
  CharacterCodes2[CharacterCodes2["_0"] = 48] = "_0";
  CharacterCodes2[CharacterCodes2["_1"] = 49] = "_1";
  CharacterCodes2[CharacterCodes2["_2"] = 50] = "_2";
  CharacterCodes2[CharacterCodes2["_3"] = 51] = "_3";
  CharacterCodes2[CharacterCodes2["_4"] = 52] = "_4";
  CharacterCodes2[CharacterCodes2["_5"] = 53] = "_5";
  CharacterCodes2[CharacterCodes2["_6"] = 54] = "_6";
  CharacterCodes2[CharacterCodes2["_7"] = 55] = "_7";
  CharacterCodes2[CharacterCodes2["_8"] = 56] = "_8";
  CharacterCodes2[CharacterCodes2["_9"] = 57] = "_9";
  CharacterCodes2[CharacterCodes2["a"] = 97] = "a";
  CharacterCodes2[CharacterCodes2["b"] = 98] = "b";
  CharacterCodes2[CharacterCodes2["c"] = 99] = "c";
  CharacterCodes2[CharacterCodes2["d"] = 100] = "d";
  CharacterCodes2[CharacterCodes2["e"] = 101] = "e";
  CharacterCodes2[CharacterCodes2["f"] = 102] = "f";
  CharacterCodes2[CharacterCodes2["g"] = 103] = "g";
  CharacterCodes2[CharacterCodes2["h"] = 104] = "h";
  CharacterCodes2[CharacterCodes2["i"] = 105] = "i";
  CharacterCodes2[CharacterCodes2["j"] = 106] = "j";
  CharacterCodes2[CharacterCodes2["k"] = 107] = "k";
  CharacterCodes2[CharacterCodes2["l"] = 108] = "l";
  CharacterCodes2[CharacterCodes2["m"] = 109] = "m";
  CharacterCodes2[CharacterCodes2["n"] = 110] = "n";
  CharacterCodes2[CharacterCodes2["o"] = 111] = "o";
  CharacterCodes2[CharacterCodes2["p"] = 112] = "p";
  CharacterCodes2[CharacterCodes2["q"] = 113] = "q";
  CharacterCodes2[CharacterCodes2["r"] = 114] = "r";
  CharacterCodes2[CharacterCodes2["s"] = 115] = "s";
  CharacterCodes2[CharacterCodes2["t"] = 116] = "t";
  CharacterCodes2[CharacterCodes2["u"] = 117] = "u";
  CharacterCodes2[CharacterCodes2["v"] = 118] = "v";
  CharacterCodes2[CharacterCodes2["w"] = 119] = "w";
  CharacterCodes2[CharacterCodes2["x"] = 120] = "x";
  CharacterCodes2[CharacterCodes2["y"] = 121] = "y";
  CharacterCodes2[CharacterCodes2["z"] = 122] = "z";
  CharacterCodes2[CharacterCodes2["A"] = 65] = "A";
  CharacterCodes2[CharacterCodes2["B"] = 66] = "B";
  CharacterCodes2[CharacterCodes2["C"] = 67] = "C";
  CharacterCodes2[CharacterCodes2["D"] = 68] = "D";
  CharacterCodes2[CharacterCodes2["E"] = 69] = "E";
  CharacterCodes2[CharacterCodes2["F"] = 70] = "F";
  CharacterCodes2[CharacterCodes2["G"] = 71] = "G";
  CharacterCodes2[CharacterCodes2["H"] = 72] = "H";
  CharacterCodes2[CharacterCodes2["I"] = 73] = "I";
  CharacterCodes2[CharacterCodes2["J"] = 74] = "J";
  CharacterCodes2[CharacterCodes2["K"] = 75] = "K";
  CharacterCodes2[CharacterCodes2["L"] = 76] = "L";
  CharacterCodes2[CharacterCodes2["M"] = 77] = "M";
  CharacterCodes2[CharacterCodes2["N"] = 78] = "N";
  CharacterCodes2[CharacterCodes2["O"] = 79] = "O";
  CharacterCodes2[CharacterCodes2["P"] = 80] = "P";
  CharacterCodes2[CharacterCodes2["Q"] = 81] = "Q";
  CharacterCodes2[CharacterCodes2["R"] = 82] = "R";
  CharacterCodes2[CharacterCodes2["S"] = 83] = "S";
  CharacterCodes2[CharacterCodes2["T"] = 84] = "T";
  CharacterCodes2[CharacterCodes2["U"] = 85] = "U";
  CharacterCodes2[CharacterCodes2["V"] = 86] = "V";
  CharacterCodes2[CharacterCodes2["W"] = 87] = "W";
  CharacterCodes2[CharacterCodes2["X"] = 88] = "X";
  CharacterCodes2[CharacterCodes2["Y"] = 89] = "Y";
  CharacterCodes2[CharacterCodes2["Z"] = 90] = "Z";
  CharacterCodes2[CharacterCodes2["asterisk"] = 42] = "asterisk";
  CharacterCodes2[CharacterCodes2["backslash"] = 92] = "backslash";
  CharacterCodes2[CharacterCodes2["closeBrace"] = 125] = "closeBrace";
  CharacterCodes2[CharacterCodes2["closeBracket"] = 93] = "closeBracket";
  CharacterCodes2[CharacterCodes2["colon"] = 58] = "colon";
  CharacterCodes2[CharacterCodes2["comma"] = 44] = "comma";
  CharacterCodes2[CharacterCodes2["dot"] = 46] = "dot";
  CharacterCodes2[CharacterCodes2["doubleQuote"] = 34] = "doubleQuote";
  CharacterCodes2[CharacterCodes2["minus"] = 45] = "minus";
  CharacterCodes2[CharacterCodes2["openBrace"] = 123] = "openBrace";
  CharacterCodes2[CharacterCodes2["openBracket"] = 91] = "openBracket";
  CharacterCodes2[CharacterCodes2["plus"] = 43] = "plus";
  CharacterCodes2[CharacterCodes2["slash"] = 47] = "slash";
  CharacterCodes2[CharacterCodes2["formFeed"] = 12] = "formFeed";
  CharacterCodes2[CharacterCodes2["tab"] = 9] = "tab";
})(CharacterCodes || (CharacterCodes = {}));

// node_modules/jsonc-parser/lib/esm/impl/string-intern.js
var cachedSpaces = new Array(20).fill(0).map((_, index) => {
  return " ".repeat(index);
});
var maxCachedValues = 200;
var cachedBreakLinesWithSpaces = {
  " ": {
    "\n": new Array(maxCachedValues).fill(0).map((_, index) => {
      return "\n" + " ".repeat(index);
    }),
    "\r": new Array(maxCachedValues).fill(0).map((_, index) => {
      return "\r" + " ".repeat(index);
    }),
    "\r\n": new Array(maxCachedValues).fill(0).map((_, index) => {
      return "\r\n" + " ".repeat(index);
    })
  },
  "	": {
    "\n": new Array(maxCachedValues).fill(0).map((_, index) => {
      return "\n" + "	".repeat(index);
    }),
    "\r": new Array(maxCachedValues).fill(0).map((_, index) => {
      return "\r" + "	".repeat(index);
    }),
    "\r\n": new Array(maxCachedValues).fill(0).map((_, index) => {
      return "\r\n" + "	".repeat(index);
    })
  }
};
var supportedEols = ["\n", "\r", "\r\n"];

// node_modules/jsonc-parser/lib/esm/impl/format.js
function format(documentText, range, options) {
  let initialIndentLevel;
  let formatText;
  let formatTextStart;
  let rangeStart;
  let rangeEnd;
  if (range) {
    rangeStart = range.offset;
    rangeEnd = rangeStart + range.length;
    formatTextStart = rangeStart;
    while (formatTextStart > 0 && !isEOL(documentText, formatTextStart - 1)) {
      formatTextStart--;
    }
    let endOffset = rangeEnd;
    while (endOffset < documentText.length && !isEOL(documentText, endOffset)) {
      endOffset++;
    }
    formatText = documentText.substring(formatTextStart, endOffset);
    initialIndentLevel = computeIndentLevel(formatText, options);
  } else {
    formatText = documentText;
    initialIndentLevel = 0;
    formatTextStart = 0;
    rangeStart = 0;
    rangeEnd = documentText.length;
  }
  const eol = getEOL(options, documentText);
  const eolFastPathSupported = supportedEols.includes(eol);
  let numberLineBreaks = 0;
  let indentLevel = 0;
  let indentValue;
  if (options.insertSpaces) {
    indentValue = cachedSpaces[options.tabSize || 4] ?? repeat(cachedSpaces[1], options.tabSize || 4);
  } else {
    indentValue = "	";
  }
  const indentType = indentValue === "	" ? "	" : " ";
  let scanner = createScanner(formatText, false);
  let hasError = false;
  function newLinesAndIndent() {
    if (numberLineBreaks > 1) {
      return repeat(eol, numberLineBreaks) + repeat(indentValue, initialIndentLevel + indentLevel);
    }
    const amountOfSpaces = indentValue.length * (initialIndentLevel + indentLevel);
    if (!eolFastPathSupported || amountOfSpaces > cachedBreakLinesWithSpaces[indentType][eol].length) {
      return eol + repeat(indentValue, initialIndentLevel + indentLevel);
    }
    if (amountOfSpaces <= 0) {
      return eol;
    }
    return cachedBreakLinesWithSpaces[indentType][eol][amountOfSpaces];
  }
  function scanNext() {
    let token = scanner.scan();
    numberLineBreaks = 0;
    while (token === 15 || token === 14) {
      if (token === 14 && options.keepLines) {
        numberLineBreaks += 1;
      } else if (token === 14) {
        numberLineBreaks = 1;
      }
      token = scanner.scan();
    }
    hasError = token === 16 || scanner.getTokenError() !== 0;
    return token;
  }
  const editOperations = [];
  function addEdit(text, startOffset, endOffset) {
    if (!hasError && (!range || startOffset < rangeEnd && endOffset > rangeStart) && documentText.substring(startOffset, endOffset) !== text) {
      editOperations.push({ offset: startOffset, length: endOffset - startOffset, content: text });
    }
  }
  let firstToken = scanNext();
  if (options.keepLines && numberLineBreaks > 0) {
    addEdit(repeat(eol, numberLineBreaks), 0, 0);
  }
  if (firstToken !== 17) {
    let firstTokenStart = scanner.getTokenOffset() + formatTextStart;
    let initialIndent = indentValue.length * initialIndentLevel < 20 && options.insertSpaces ? cachedSpaces[indentValue.length * initialIndentLevel] : repeat(indentValue, initialIndentLevel);
    addEdit(initialIndent, formatTextStart, firstTokenStart);
  }
  while (firstToken !== 17) {
    let firstTokenEnd = scanner.getTokenOffset() + scanner.getTokenLength() + formatTextStart;
    let secondToken = scanNext();
    let replaceContent = "";
    let needsLineBreak = false;
    while (numberLineBreaks === 0 && (secondToken === 12 || secondToken === 13)) {
      let commentTokenStart = scanner.getTokenOffset() + formatTextStart;
      addEdit(cachedSpaces[1], firstTokenEnd, commentTokenStart);
      firstTokenEnd = scanner.getTokenOffset() + scanner.getTokenLength() + formatTextStart;
      needsLineBreak = secondToken === 12;
      replaceContent = needsLineBreak ? newLinesAndIndent() : "";
      secondToken = scanNext();
    }
    if (secondToken === 2) {
      if (firstToken !== 1) {
        indentLevel--;
      }
      ;
      if (options.keepLines && numberLineBreaks > 0 || !options.keepLines && firstToken !== 1) {
        replaceContent = newLinesAndIndent();
      } else if (options.keepLines) {
        replaceContent = cachedSpaces[1];
      }
    } else if (secondToken === 4) {
      if (firstToken !== 3) {
        indentLevel--;
      }
      ;
      if (options.keepLines && numberLineBreaks > 0 || !options.keepLines && firstToken !== 3) {
        replaceContent = newLinesAndIndent();
      } else if (options.keepLines) {
        replaceContent = cachedSpaces[1];
      }
    } else {
      switch (firstToken) {
        case 3:
        case 1:
          indentLevel++;
          if (options.keepLines && numberLineBreaks > 0 || !options.keepLines) {
            replaceContent = newLinesAndIndent();
          } else {
            replaceContent = cachedSpaces[1];
          }
          break;
        case 5:
          if (options.keepLines && numberLineBreaks > 0 || !options.keepLines) {
            replaceContent = newLinesAndIndent();
          } else {
            replaceContent = cachedSpaces[1];
          }
          break;
        case 12:
          replaceContent = newLinesAndIndent();
          break;
        case 13:
          if (numberLineBreaks > 0) {
            replaceContent = newLinesAndIndent();
          } else if (!needsLineBreak) {
            replaceContent = cachedSpaces[1];
          }
          break;
        case 6:
          if (options.keepLines && numberLineBreaks > 0) {
            replaceContent = newLinesAndIndent();
          } else if (!needsLineBreak) {
            replaceContent = cachedSpaces[1];
          }
          break;
        case 10:
          if (options.keepLines && numberLineBreaks > 0) {
            replaceContent = newLinesAndIndent();
          } else if (secondToken === 6 && !needsLineBreak) {
            replaceContent = "";
          }
          break;
        case 7:
        case 8:
        case 9:
        case 11:
        case 2:
        case 4:
          if (options.keepLines && numberLineBreaks > 0) {
            replaceContent = newLinesAndIndent();
          } else {
            if ((secondToken === 12 || secondToken === 13) && !needsLineBreak) {
              replaceContent = cachedSpaces[1];
            } else if (secondToken !== 5 && secondToken !== 17) {
              hasError = true;
            }
          }
          break;
        case 16:
          hasError = true;
          break;
      }
      if (numberLineBreaks > 0 && (secondToken === 12 || secondToken === 13)) {
        replaceContent = newLinesAndIndent();
      }
    }
    if (secondToken === 17) {
      if (options.keepLines && numberLineBreaks > 0) {
        replaceContent = newLinesAndIndent();
      } else {
        replaceContent = options.insertFinalNewline ? eol : "";
      }
    }
    const secondTokenStart = scanner.getTokenOffset() + formatTextStart;
    addEdit(replaceContent, firstTokenEnd, secondTokenStart);
    firstToken = secondToken;
  }
  return editOperations;
}
function repeat(s, count) {
  let result = "";
  for (let i = 0; i < count; i++) {
    result += s;
  }
  return result;
}
function computeIndentLevel(content, options) {
  let i = 0;
  let nChars = 0;
  const tabSize = options.tabSize || 4;
  while (i < content.length) {
    let ch = content.charAt(i);
    if (ch === cachedSpaces[1]) {
      nChars++;
    } else if (ch === "	") {
      nChars += tabSize;
    } else {
      break;
    }
    i++;
  }
  return Math.floor(nChars / tabSize);
}
function getEOL(options, text) {
  for (let i = 0; i < text.length; i++) {
    const ch = text.charAt(i);
    if (ch === "\r") {
      if (i + 1 < text.length && text.charAt(i + 1) === "\n") {
        return "\r\n";
      }
      return "\r";
    } else if (ch === "\n") {
      return "\n";
    }
  }
  return options && options.eol || "\n";
}
function isEOL(text, offset) {
  return "\r\n".indexOf(text.charAt(offset)) !== -1;
}

// node_modules/jsonc-parser/lib/esm/impl/parser.js
var ParseOptions;
(function(ParseOptions2) {
  ParseOptions2.DEFAULT = {
    allowTrailingComma: false
  };
})(ParseOptions || (ParseOptions = {}));
function parse(text, errors = [], options = ParseOptions.DEFAULT) {
  let currentProperty = null;
  let currentParent = [];
  const previousParents = [];
  function onValue(value) {
    if (Array.isArray(currentParent)) {
      currentParent.push(value);
    } else if (currentProperty !== null) {
      currentParent[currentProperty] = value;
    }
  }
  const visitor = {
    onObjectBegin: () => {
      const object = {};
      onValue(object);
      previousParents.push(currentParent);
      currentParent = object;
      currentProperty = null;
    },
    onObjectProperty: (name) => {
      currentProperty = name;
    },
    onObjectEnd: () => {
      currentParent = previousParents.pop();
    },
    onArrayBegin: () => {
      const array = [];
      onValue(array);
      previousParents.push(currentParent);
      currentParent = array;
      currentProperty = null;
    },
    onArrayEnd: () => {
      currentParent = previousParents.pop();
    },
    onLiteralValue: onValue,
    onError: (error, offset, length) => {
      errors.push({ error, offset, length });
    }
  };
  visit(text, visitor, options);
  return currentParent[0];
}
function parseTree(text, errors = [], options = ParseOptions.DEFAULT) {
  let currentParent = { type: "array", offset: -1, length: -1, children: [], parent: void 0 };
  function ensurePropertyComplete(endOffset) {
    if (currentParent.type === "property") {
      currentParent.length = endOffset - currentParent.offset;
      currentParent = currentParent.parent;
    }
  }
  function onValue(valueNode) {
    currentParent.children.push(valueNode);
    return valueNode;
  }
  const visitor = {
    onObjectBegin: (offset) => {
      currentParent = onValue({ type: "object", offset, length: -1, parent: currentParent, children: [] });
    },
    onObjectProperty: (name, offset, length) => {
      currentParent = onValue({ type: "property", offset, length: -1, parent: currentParent, children: [] });
      currentParent.children.push({ type: "string", value: name, offset, length, parent: currentParent });
    },
    onObjectEnd: (offset, length) => {
      ensurePropertyComplete(offset + length);
      currentParent.length = offset + length - currentParent.offset;
      currentParent = currentParent.parent;
      ensurePropertyComplete(offset + length);
    },
    onArrayBegin: (offset, length) => {
      currentParent = onValue({ type: "array", offset, length: -1, parent: currentParent, children: [] });
    },
    onArrayEnd: (offset, length) => {
      currentParent.length = offset + length - currentParent.offset;
      currentParent = currentParent.parent;
      ensurePropertyComplete(offset + length);
    },
    onLiteralValue: (value, offset, length) => {
      onValue({ type: getNodeType(value), offset, length, parent: currentParent, value });
      ensurePropertyComplete(offset + length);
    },
    onSeparator: (sep, offset, length) => {
      if (currentParent.type === "property") {
        if (sep === ":") {
          currentParent.colonOffset = offset;
        } else if (sep === ",") {
          ensurePropertyComplete(offset);
        }
      }
    },
    onError: (error, offset, length) => {
      errors.push({ error, offset, length });
    }
  };
  visit(text, visitor, options);
  const result = currentParent.children[0];
  if (result) {
    delete result.parent;
  }
  return result;
}
function findNodeAtLocation(root, path3) {
  if (!root) {
    return void 0;
  }
  let node = root;
  for (let segment of path3) {
    if (typeof segment === "string") {
      if (node.type !== "object" || !Array.isArray(node.children)) {
        return void 0;
      }
      let found = false;
      for (const propertyNode of node.children) {
        if (Array.isArray(propertyNode.children) && propertyNode.children[0].value === segment && propertyNode.children.length === 2) {
          node = propertyNode.children[1];
          found = true;
          break;
        }
      }
      if (!found) {
        return void 0;
      }
    } else {
      const index = segment;
      if (node.type !== "array" || index < 0 || !Array.isArray(node.children) || index >= node.children.length) {
        return void 0;
      }
      node = node.children[index];
    }
  }
  return node;
}
function visit(text, visitor, options = ParseOptions.DEFAULT) {
  const _scanner = createScanner(text, false);
  const _jsonPath = [];
  let suppressedCallbacks = 0;
  function toNoArgVisit(visitFunction) {
    return visitFunction ? () => suppressedCallbacks === 0 && visitFunction(_scanner.getTokenOffset(), _scanner.getTokenLength(), _scanner.getTokenStartLine(), _scanner.getTokenStartCharacter()) : () => true;
  }
  function toOneArgVisit(visitFunction) {
    return visitFunction ? (arg) => suppressedCallbacks === 0 && visitFunction(arg, _scanner.getTokenOffset(), _scanner.getTokenLength(), _scanner.getTokenStartLine(), _scanner.getTokenStartCharacter()) : () => true;
  }
  function toOneArgVisitWithPath(visitFunction) {
    return visitFunction ? (arg) => suppressedCallbacks === 0 && visitFunction(arg, _scanner.getTokenOffset(), _scanner.getTokenLength(), _scanner.getTokenStartLine(), _scanner.getTokenStartCharacter(), () => _jsonPath.slice()) : () => true;
  }
  function toBeginVisit(visitFunction) {
    return visitFunction ? () => {
      if (suppressedCallbacks > 0) {
        suppressedCallbacks++;
      } else {
        let cbReturn = visitFunction(_scanner.getTokenOffset(), _scanner.getTokenLength(), _scanner.getTokenStartLine(), _scanner.getTokenStartCharacter(), () => _jsonPath.slice());
        if (cbReturn === false) {
          suppressedCallbacks = 1;
        }
      }
    } : () => true;
  }
  function toEndVisit(visitFunction) {
    return visitFunction ? () => {
      if (suppressedCallbacks > 0) {
        suppressedCallbacks--;
      }
      if (suppressedCallbacks === 0) {
        visitFunction(_scanner.getTokenOffset(), _scanner.getTokenLength(), _scanner.getTokenStartLine(), _scanner.getTokenStartCharacter());
      }
    } : () => true;
  }
  const onObjectBegin = toBeginVisit(visitor.onObjectBegin), onObjectProperty = toOneArgVisitWithPath(visitor.onObjectProperty), onObjectEnd = toEndVisit(visitor.onObjectEnd), onArrayBegin = toBeginVisit(visitor.onArrayBegin), onArrayEnd = toEndVisit(visitor.onArrayEnd), onLiteralValue = toOneArgVisitWithPath(visitor.onLiteralValue), onSeparator = toOneArgVisit(visitor.onSeparator), onComment = toNoArgVisit(visitor.onComment), onError = toOneArgVisit(visitor.onError);
  const disallowComments = options && options.disallowComments;
  const allowTrailingComma = options && options.allowTrailingComma;
  function scanNext() {
    while (true) {
      const token = _scanner.scan();
      switch (_scanner.getTokenError()) {
        case 4:
          handleError(
            14
            /* ParseErrorCode.InvalidUnicode */
          );
          break;
        case 5:
          handleError(
            15
            /* ParseErrorCode.InvalidEscapeCharacter */
          );
          break;
        case 3:
          handleError(
            13
            /* ParseErrorCode.UnexpectedEndOfNumber */
          );
          break;
        case 1:
          if (!disallowComments) {
            handleError(
              11
              /* ParseErrorCode.UnexpectedEndOfComment */
            );
          }
          break;
        case 2:
          handleError(
            12
            /* ParseErrorCode.UnexpectedEndOfString */
          );
          break;
        case 6:
          handleError(
            16
            /* ParseErrorCode.InvalidCharacter */
          );
          break;
      }
      switch (token) {
        case 12:
        case 13:
          if (disallowComments) {
            handleError(
              10
              /* ParseErrorCode.InvalidCommentToken */
            );
          } else {
            onComment();
          }
          break;
        case 16:
          handleError(
            1
            /* ParseErrorCode.InvalidSymbol */
          );
          break;
        case 15:
        case 14:
          break;
        default:
          return token;
      }
    }
  }
  function handleError(error, skipUntilAfter = [], skipUntil = []) {
    onError(error);
    if (skipUntilAfter.length + skipUntil.length > 0) {
      let token = _scanner.getToken();
      while (token !== 17) {
        if (skipUntilAfter.indexOf(token) !== -1) {
          scanNext();
          break;
        } else if (skipUntil.indexOf(token) !== -1) {
          break;
        }
        token = scanNext();
      }
    }
  }
  function parseString(isValue) {
    const value = _scanner.getTokenValue();
    if (isValue) {
      onLiteralValue(value);
    } else {
      onObjectProperty(value);
      _jsonPath.push(value);
    }
    scanNext();
    return true;
  }
  function parseLiteral() {
    switch (_scanner.getToken()) {
      case 11:
        const tokenValue = _scanner.getTokenValue();
        let value = Number(tokenValue);
        if (isNaN(value)) {
          handleError(
            2
            /* ParseErrorCode.InvalidNumberFormat */
          );
          value = 0;
        }
        onLiteralValue(value);
        break;
      case 7:
        onLiteralValue(null);
        break;
      case 8:
        onLiteralValue(true);
        break;
      case 9:
        onLiteralValue(false);
        break;
      default:
        return false;
    }
    scanNext();
    return true;
  }
  function parseProperty() {
    if (_scanner.getToken() !== 10) {
      handleError(3, [], [
        2,
        5
        /* SyntaxKind.CommaToken */
      ]);
      return false;
    }
    parseString(false);
    if (_scanner.getToken() === 6) {
      onSeparator(":");
      scanNext();
      if (!parseValue()) {
        handleError(4, [], [
          2,
          5
          /* SyntaxKind.CommaToken */
        ]);
      }
    } else {
      handleError(5, [], [
        2,
        5
        /* SyntaxKind.CommaToken */
      ]);
    }
    _jsonPath.pop();
    return true;
  }
  function parseObject() {
    onObjectBegin();
    scanNext();
    let needsComma = false;
    while (_scanner.getToken() !== 2 && _scanner.getToken() !== 17) {
      if (_scanner.getToken() === 5) {
        if (!needsComma) {
          handleError(4, [], []);
        }
        onSeparator(",");
        scanNext();
        if (_scanner.getToken() === 2 && allowTrailingComma) {
          break;
        }
      } else if (needsComma) {
        handleError(6, [], []);
      }
      if (!parseProperty()) {
        handleError(4, [], [
          2,
          5
          /* SyntaxKind.CommaToken */
        ]);
      }
      needsComma = true;
    }
    onObjectEnd();
    if (_scanner.getToken() !== 2) {
      handleError(7, [
        2
        /* SyntaxKind.CloseBraceToken */
      ], []);
    } else {
      scanNext();
    }
    return true;
  }
  function parseArray() {
    onArrayBegin();
    scanNext();
    let isFirstElement = true;
    let needsComma = false;
    while (_scanner.getToken() !== 4 && _scanner.getToken() !== 17) {
      if (_scanner.getToken() === 5) {
        if (!needsComma) {
          handleError(4, [], []);
        }
        onSeparator(",");
        scanNext();
        if (_scanner.getToken() === 4 && allowTrailingComma) {
          break;
        }
      } else if (needsComma) {
        handleError(6, [], []);
      }
      if (isFirstElement) {
        _jsonPath.push(0);
        isFirstElement = false;
      } else {
        _jsonPath[_jsonPath.length - 1]++;
      }
      if (!parseValue()) {
        handleError(4, [], [
          4,
          5
          /* SyntaxKind.CommaToken */
        ]);
      }
      needsComma = true;
    }
    onArrayEnd();
    if (!isFirstElement) {
      _jsonPath.pop();
    }
    if (_scanner.getToken() !== 4) {
      handleError(8, [
        4
        /* SyntaxKind.CloseBracketToken */
      ], []);
    } else {
      scanNext();
    }
    return true;
  }
  function parseValue() {
    switch (_scanner.getToken()) {
      case 3:
        return parseArray();
      case 1:
        return parseObject();
      case 10:
        return parseString(true);
      default:
        return parseLiteral();
    }
  }
  scanNext();
  if (_scanner.getToken() === 17) {
    if (options.allowEmptyContent) {
      return true;
    }
    handleError(4, [], []);
    return false;
  }
  if (!parseValue()) {
    handleError(4, [], []);
    return false;
  }
  if (_scanner.getToken() !== 17) {
    handleError(9, [], []);
  }
  return true;
}
function getNodeType(value) {
  switch (typeof value) {
    case "boolean":
      return "boolean";
    case "number":
      return "number";
    case "string":
      return "string";
    case "object": {
      if (!value) {
        return "null";
      } else if (Array.isArray(value)) {
        return "array";
      }
      return "object";
    }
    default:
      return "null";
  }
}

// node_modules/jsonc-parser/lib/esm/impl/edit.js
function setProperty(text, originalPath, value, options) {
  const path3 = originalPath.slice();
  const errors = [];
  const root = parseTree(text, errors);
  let parent = void 0;
  let lastSegment = void 0;
  while (path3.length > 0) {
    lastSegment = path3.pop();
    parent = findNodeAtLocation(root, path3);
    if (parent === void 0 && value !== void 0) {
      if (typeof lastSegment === "string") {
        value = { [lastSegment]: value };
      } else {
        value = [value];
      }
    } else {
      break;
    }
  }
  if (!parent) {
    if (value === void 0) {
      throw new Error("Can not delete in empty document");
    }
    return withFormatting(text, { offset: root ? root.offset : 0, length: root ? root.length : 0, content: JSON.stringify(value) }, options);
  } else if (parent.type === "object" && typeof lastSegment === "string" && Array.isArray(parent.children)) {
    const existing = findNodeAtLocation(parent, [lastSegment]);
    if (existing !== void 0) {
      if (value === void 0) {
        if (!existing.parent) {
          throw new Error("Malformed AST");
        }
        const propertyIndex = parent.children.indexOf(existing.parent);
        let removeBegin;
        let removeEnd = existing.parent.offset + existing.parent.length;
        if (propertyIndex > 0) {
          let previous = parent.children[propertyIndex - 1];
          removeBegin = previous.offset + previous.length;
        } else {
          removeBegin = parent.offset + 1;
          if (parent.children.length > 1) {
            let next = parent.children[1];
            removeEnd = next.offset;
          }
        }
        return withFormatting(text, { offset: removeBegin, length: removeEnd - removeBegin, content: "" }, options);
      } else {
        return withFormatting(text, { offset: existing.offset, length: existing.length, content: JSON.stringify(value) }, options);
      }
    } else {
      if (value === void 0) {
        return [];
      }
      const newProperty = `${JSON.stringify(lastSegment)}: ${JSON.stringify(value)}`;
      const index = options.getInsertionIndex ? options.getInsertionIndex(parent.children.map((p) => p.children[0].value)) : parent.children.length;
      let edit;
      if (index > 0) {
        let previous = parent.children[index - 1];
        edit = { offset: previous.offset + previous.length, length: 0, content: "," + newProperty };
      } else if (parent.children.length === 0) {
        edit = { offset: parent.offset + 1, length: 0, content: newProperty };
      } else {
        edit = { offset: parent.offset + 1, length: 0, content: newProperty + "," };
      }
      return withFormatting(text, edit, options);
    }
  } else if (parent.type === "array" && typeof lastSegment === "number" && Array.isArray(parent.children)) {
    const insertIndex = lastSegment;
    if (insertIndex === -1) {
      const newProperty = `${JSON.stringify(value)}`;
      let edit;
      if (parent.children.length === 0) {
        edit = { offset: parent.offset + 1, length: 0, content: newProperty };
      } else {
        const previous = parent.children[parent.children.length - 1];
        edit = { offset: previous.offset + previous.length, length: 0, content: "," + newProperty };
      }
      return withFormatting(text, edit, options);
    } else if (value === void 0 && parent.children.length >= 0) {
      const removalIndex = lastSegment;
      const toRemove = parent.children[removalIndex];
      let edit;
      if (parent.children.length === 1) {
        edit = { offset: parent.offset + 1, length: parent.length - 2, content: "" };
      } else if (parent.children.length - 1 === removalIndex) {
        let previous = parent.children[removalIndex - 1];
        let offset = previous.offset + previous.length;
        let parentEndOffset = parent.offset + parent.length;
        edit = { offset, length: parentEndOffset - 2 - offset, content: "" };
      } else {
        edit = { offset: toRemove.offset, length: parent.children[removalIndex + 1].offset - toRemove.offset, content: "" };
      }
      return withFormatting(text, edit, options);
    } else if (value !== void 0) {
      let edit;
      const newProperty = `${JSON.stringify(value)}`;
      if (!options.isArrayInsertion && parent.children.length > lastSegment) {
        const toModify = parent.children[lastSegment];
        edit = { offset: toModify.offset, length: toModify.length, content: newProperty };
      } else if (parent.children.length === 0 || lastSegment === 0) {
        edit = { offset: parent.offset + 1, length: 0, content: parent.children.length === 0 ? newProperty : newProperty + "," };
      } else {
        const index = lastSegment > parent.children.length ? parent.children.length : lastSegment;
        const previous = parent.children[index - 1];
        edit = { offset: previous.offset + previous.length, length: 0, content: "," + newProperty };
      }
      return withFormatting(text, edit, options);
    } else {
      throw new Error(`Can not ${value === void 0 ? "remove" : options.isArrayInsertion ? "insert" : "modify"} Array index ${insertIndex} as length is not sufficient`);
    }
  } else {
    throw new Error(`Can not add ${typeof lastSegment !== "number" ? "index" : "property"} to parent of type ${parent.type}`);
  }
}
function withFormatting(text, edit, options) {
  if (!options.formattingOptions) {
    return [edit];
  }
  let newText = applyEdit(text, edit);
  let begin = edit.offset;
  let end = edit.offset + edit.content.length;
  if (edit.length === 0 || edit.content.length === 0) {
    while (begin > 0 && !isEOL(newText, begin - 1)) {
      begin--;
    }
    while (end < newText.length && !isEOL(newText, end)) {
      end++;
    }
  }
  const edits = format(newText, { offset: begin, length: end - begin }, { ...options.formattingOptions, keepLines: false });
  for (let i = edits.length - 1; i >= 0; i--) {
    const edit2 = edits[i];
    newText = applyEdit(newText, edit2);
    begin = Math.min(begin, edit2.offset);
    end = Math.max(end, edit2.offset + edit2.length);
    end += edit2.content.length - edit2.length;
  }
  const editLength = text.length - (newText.length - end) - begin;
  return [{ offset: begin, length: editLength, content: newText.substring(begin, end) }];
}
function applyEdit(text, edit) {
  return text.substring(0, edit.offset) + edit.content + text.substring(edit.offset + edit.length);
}

// node_modules/jsonc-parser/lib/esm/main.js
var ScanError;
(function(ScanError2) {
  ScanError2[ScanError2["None"] = 0] = "None";
  ScanError2[ScanError2["UnexpectedEndOfComment"] = 1] = "UnexpectedEndOfComment";
  ScanError2[ScanError2["UnexpectedEndOfString"] = 2] = "UnexpectedEndOfString";
  ScanError2[ScanError2["UnexpectedEndOfNumber"] = 3] = "UnexpectedEndOfNumber";
  ScanError2[ScanError2["InvalidUnicode"] = 4] = "InvalidUnicode";
  ScanError2[ScanError2["InvalidEscapeCharacter"] = 5] = "InvalidEscapeCharacter";
  ScanError2[ScanError2["InvalidCharacter"] = 6] = "InvalidCharacter";
})(ScanError || (ScanError = {}));
var SyntaxKind;
(function(SyntaxKind2) {
  SyntaxKind2[SyntaxKind2["OpenBraceToken"] = 1] = "OpenBraceToken";
  SyntaxKind2[SyntaxKind2["CloseBraceToken"] = 2] = "CloseBraceToken";
  SyntaxKind2[SyntaxKind2["OpenBracketToken"] = 3] = "OpenBracketToken";
  SyntaxKind2[SyntaxKind2["CloseBracketToken"] = 4] = "CloseBracketToken";
  SyntaxKind2[SyntaxKind2["CommaToken"] = 5] = "CommaToken";
  SyntaxKind2[SyntaxKind2["ColonToken"] = 6] = "ColonToken";
  SyntaxKind2[SyntaxKind2["NullKeyword"] = 7] = "NullKeyword";
  SyntaxKind2[SyntaxKind2["TrueKeyword"] = 8] = "TrueKeyword";
  SyntaxKind2[SyntaxKind2["FalseKeyword"] = 9] = "FalseKeyword";
  SyntaxKind2[SyntaxKind2["StringLiteral"] = 10] = "StringLiteral";
  SyntaxKind2[SyntaxKind2["NumericLiteral"] = 11] = "NumericLiteral";
  SyntaxKind2[SyntaxKind2["LineCommentTrivia"] = 12] = "LineCommentTrivia";
  SyntaxKind2[SyntaxKind2["BlockCommentTrivia"] = 13] = "BlockCommentTrivia";
  SyntaxKind2[SyntaxKind2["LineBreakTrivia"] = 14] = "LineBreakTrivia";
  SyntaxKind2[SyntaxKind2["Trivia"] = 15] = "Trivia";
  SyntaxKind2[SyntaxKind2["Unknown"] = 16] = "Unknown";
  SyntaxKind2[SyntaxKind2["EOF"] = 17] = "EOF";
})(SyntaxKind || (SyntaxKind = {}));
var parse2 = parse;
var parseTree2 = parseTree;
var ParseErrorCode;
(function(ParseErrorCode2) {
  ParseErrorCode2[ParseErrorCode2["InvalidSymbol"] = 1] = "InvalidSymbol";
  ParseErrorCode2[ParseErrorCode2["InvalidNumberFormat"] = 2] = "InvalidNumberFormat";
  ParseErrorCode2[ParseErrorCode2["PropertyNameExpected"] = 3] = "PropertyNameExpected";
  ParseErrorCode2[ParseErrorCode2["ValueExpected"] = 4] = "ValueExpected";
  ParseErrorCode2[ParseErrorCode2["ColonExpected"] = 5] = "ColonExpected";
  ParseErrorCode2[ParseErrorCode2["CommaExpected"] = 6] = "CommaExpected";
  ParseErrorCode2[ParseErrorCode2["CloseBraceExpected"] = 7] = "CloseBraceExpected";
  ParseErrorCode2[ParseErrorCode2["CloseBracketExpected"] = 8] = "CloseBracketExpected";
  ParseErrorCode2[ParseErrorCode2["EndOfFileExpected"] = 9] = "EndOfFileExpected";
  ParseErrorCode2[ParseErrorCode2["InvalidCommentToken"] = 10] = "InvalidCommentToken";
  ParseErrorCode2[ParseErrorCode2["UnexpectedEndOfComment"] = 11] = "UnexpectedEndOfComment";
  ParseErrorCode2[ParseErrorCode2["UnexpectedEndOfString"] = 12] = "UnexpectedEndOfString";
  ParseErrorCode2[ParseErrorCode2["UnexpectedEndOfNumber"] = 13] = "UnexpectedEndOfNumber";
  ParseErrorCode2[ParseErrorCode2["InvalidUnicode"] = 14] = "InvalidUnicode";
  ParseErrorCode2[ParseErrorCode2["InvalidEscapeCharacter"] = 15] = "InvalidEscapeCharacter";
  ParseErrorCode2[ParseErrorCode2["InvalidCharacter"] = 16] = "InvalidCharacter";
})(ParseErrorCode || (ParseErrorCode = {}));
function modify(text, path3, value, options) {
  return setProperty(text, path3, value, options);
}
function applyEdits(text, edits) {
  let sortedEdits = edits.slice(0).sort((a, b) => {
    const diff = a.offset - b.offset;
    if (diff === 0) {
      return a.length - b.length;
    }
    return diff;
  });
  let lastModifiedOffset = text.length;
  for (let i = sortedEdits.length - 1; i >= 0; i--) {
    let e = sortedEdits[i];
    if (e.offset + e.length <= lastModifiedOffset) {
      text = applyEdit(text, e);
    } else {
      throw new Error("Overlapping edit");
    }
    lastModifiedOffset = e.offset;
  }
  return text;
}

// src/setup/storage.mjs
var MAX_FILE_BYTES = 1024 * 1024;
function fingerprint(value) {
  const canonical = (value2) => Array.isArray(value2) ? value2.map(canonical) : isObject(value2) ? Object.fromEntries(Object.keys(value2).sort().map((key) => [key, canonical(value2[key])])) : value2;
  return createHash3("sha256").update(JSON.stringify(canonical(value))).digest("hex");
}
async function assertSafePath(file) {
  const parsed = path.parse(file);
  let current = parsed.root;
  for (const segment of file.slice(parsed.root.length).split(path.sep)) {
    current = path.join(current, segment);
    try {
      const stat = await lstat(current);
      if (stat.isSymbolicLink()) fail("SYMLINK", "A configuration or state path contains a symlink. Use its real directory and inspect it before setup.");
      if (current !== file && !stat.isDirectory()) fail("FILE_PATH", "A settings parent path is not a directory.");
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
    }
  }
}
async function readSnapshot(file) {
  await assertSafePath(file);
  try {
    const stat = await lstat(file);
    if (!stat.isFile() || stat.size > MAX_FILE_BYTES) fail("FILE_SIZE", "Settings must be a regular file smaller than 1 MiB.");
    return await readFile2(file, "utf8");
  } catch (error) {
    if (error.code === "ENOENT") return null;
    throw error;
  }
}
function parseConfig(text) {
  if (text === null) return {};
  const errors = [];
  const data = parse2(text, errors, { allowTrailingComma: true });
  const tree = parseTree2(text);
  const checkDuplicates = (node) => {
    if (node?.type === "object") {
      const names = node.children.map((property) => property.children[0].value);
      if (new Set(names).size !== names.length) fail("INVALID_CONFIG", "Settings contain duplicate JSON keys. Resolve them before setup.");
    }
    for (const child of node?.children ?? []) checkDuplicates(child);
  };
  checkDuplicates(tree);
  if (errors.length || !isObject(data) || "mcpServers" in data && !isObject(data.mcpServers)) {
    fail("INVALID_CONFIG", "Kiro settings are not a valid JSON/JSONC object with an mcpServers object. No settings were changed.");
  }
  return data;
}
function editConfig(text, name, entry) {
  parseConfig(text);
  const input = text ?? "{}\n";
  const eol = input.includes("\r\n") ? "\r\n" : "\n";
  return applyEdits(input, modify(input, ["mcpServers", name], entry, {
    formattingOptions: { insertSpaces: true, tabSize: 2, eol }
  }));
}
function parseState(text) {
  if (text === null) return { version: 1, connections: {} };
  let data;
  try {
    data = JSON.parse(text);
  } catch {
    fail("INVALID_STATE", "Registration state is invalid. Restore its backup before setup; no new client was registered.");
  }
  if (!isObject(data) || data.version !== 1 || !isObject(data.connections)) fail("INVALID_STATE", "Registration state has an unsupported format.");
  for (const record of Object.values(data.connections)) {
    if (!isObject(record) || !["ready", "registering", "uncertain"].includes(record.status) || ["endpoint", "issuer", "registrationEndpoint", "serverName", "configPath", "kiroVersion"].some((key) => typeof record[key] !== "string") || !Number.isInteger(record.callbackPort) || record.callbackPort < 1024 || record.callbackPort > 65535 || record.status === "ready" && (typeof record.clientId !== "string" || !record.clientId) || record.fingerprint !== void 0 && typeof record.fingerprint !== "string") {
      fail("INVALID_STATE", "A registration record is invalid. Inspect or restore state before setup.");
    }
  }
  return data;
}
async function withLock(file, action) {
  const lockPath = `${file}.lock`;
  await assertSafePath(lockPath);
  await mkdir(path.dirname(file), { recursive: true, mode: 448 });
  let handle;
  try {
    handle = await open(lockPath, "wx", 384);
  } catch (error) {
    if (error.code === "EEXIST") fail("LOCKED", "Another setup may be running. If it crashed, verify no helper is active before removing the .lock file beside its state/config.");
    throw error;
  }
  try {
    return await action();
  } finally {
    await handle.close();
    await rm(lockPath, { force: true });
  }
}
async function atomicWrite(file, original, next) {
  if (next === original) return;
  await assertSafePath(file);
  await mkdir(path.dirname(file), { recursive: true, mode: 448 });
  if (await readSnapshot(file) !== original) fail("CONCURRENT_EDIT", "Settings changed during setup. Rerun to inspect the current file; the new registration is retained.");
  const temporary = `${file}.${randomUUID()}.tmp`;
  let backup;
  try {
    const handle = await open(temporary, "wx", 384);
    try {
      await handle.writeFile(next);
      await handle.sync();
    } finally {
      await handle.close();
    }
    if (original !== null) {
      backup = `${file}.${randomUUID()}.bak`;
      const handle2 = await open(backup, "wx", 384);
      try {
        await handle2.writeFile(original);
      } finally {
        await handle2.close();
      }
    }
    if (await readSnapshot(file) !== original) fail("CONCURRENT_EDIT", "Settings changed during setup. Rerun without overwriting the current file.");
    await rename(temporary, file);
  } finally {
    await rm(temporary, { force: true });
  }
  return backup;
}

// src/setup/setup.mjs
var consentNote = "Kiro 1.1.70 may request all permissions. In n8n consent, select Custom and review workflow read/write/execute and execution read. The helper does not grant access.";
async function locations(options, home) {
  const root = await realpath(home);
  const workspace = options.workspace ? await realpath(path2.resolve(options.workspace)) : null;
  const scope = options.scope ?? "user";
  if (!["user", "workspace"].includes(scope)) fail("ARGUMENT", "--scope must be user or workspace.");
  if (scope === "workspace" && !workspace) fail("ARGUMENT", "Workspace scope requires an explicit --workspace directory.");
  return {
    statePath: path2.join(root, ".kiro/n8n-power/connections.json"),
    configPath: path2.join(scope === "user" ? root : workspace, ".kiro/settings/mcp.json"),
    overridePath: scope === "user" && workspace ? path2.join(workspace, ".kiro/settings/mcp.json") : null,
    scope
  };
}
function checkOwnership(entry, record) {
  if (entry !== void 0 && (!record?.fingerprint || ![record.fingerprint, record.previousFingerprint].includes(fingerprint(entry)))) {
    fail("CONFIG_CONFLICT", "This server entry is unmanaged or has been edited. Preserve it and choose another --name, or reconcile it manually before repair/removal.");
  }
}
async function runSetup(options, dependencies = {}) {
  const command = options.command ?? "configure";
  if (!["configure", "doctor", "repair", "remove"].includes(command)) fail("ARGUMENT", "Choose configure, doctor, repair or remove.");
  if (!options.url) fail("ARGUMENT", "--url is required to identify the intended instance.");
  if (options.newRegistration && command !== "repair") fail("ARGUMENT", "--new-registration is only available with repair.");
  if (command === "repair" && !options.newRegistration && options.callbackPort === void 0) fail("ARGUMENT", "Repair requires --new-registration or a new --callback-port. Use doctor first.");
  if (options.callbackPort !== void 0 && (!Number.isInteger(options.callbackPort) || options.callbackPort < 1024 || options.callbackPort > 65535)) fail("CALLBACK_PORT", "--callback-port must be between 1024 and 65535.");
  const endpoint = normalizeEndpoint(options.url);
  const serverName = options.name ?? defaultName(endpoint);
  if (!/^[a-zA-Z0-9][a-zA-Z0-9_-]{0,79}$/.test(serverName) || ["__proto__", "constructor", "prototype"].includes(serverName)) fail("ARGUMENT", "Use a server name of 1–80 letters, numbers, hyphens or underscores, starting with a letter or number.");
  const paths = await locations(options, dependencies.homeDir ?? homedir());
  const key = fingerprint([paths.configPath, serverName]);
  const inspect = dependencies.discover ?? discover;
  const createRegistration = dependencies.register ?? register;
  const choosePort = dependencies.availablePort ?? availablePort;
  const write = dependencies.atomicWrite ?? atomicWrite;
  const network = dependencies.network ?? {};
  const baseResult = { serverName, endpoint, scope: paths.scope, configPath: paths.configPath };
  const action = async () => {
    let stateText = await readSnapshot(paths.statePath);
    const state = parseState(stateText);
    const record = state.connections[key];
    const configText = await readSnapshot(paths.configPath);
    const config = parseConfig(configText);
    const entry = config.mcpServers?.[serverName];
    if (record && (record.endpoint !== endpoint || record.configPath !== paths.configPath || record.serverName !== serverName)) fail("STATE_CONFLICT", "The saved connection identifies a different endpoint or settings file. Use a different name.");
    checkOwnership(entry, record);
    if (paths.overridePath && command !== "remove") {
      const override = parseConfig(await readSnapshot(paths.overridePath));
      if (Object.hasOwn(override.mcpServers ?? {}, serverName)) fail("WORKSPACE_OVERRIDE", "This workspace overrides the user-level server. Select workspace scope or a different name before configuring.");
    }
    const saveState = async () => {
      const next = JSON.stringify(state, null, 2) + "\n";
      await write(paths.statePath, stateText, next);
      stateText = next;
    };
    if (command === "remove") {
      if (!record) return { ...baseResult, status: "not_managed", changed: false };
      if (options.dryRun) return { ...baseResult, status: "dry_run", action: "remove", changed: false };
      if (entry !== void 0) await write(paths.configPath, configText, editConfig(configText, serverName, void 0));
      delete state.connections[key];
      await saveState();
      return { ...baseResult, status: "removed", changed: true, next: "Revoke the grant in n8n Settings > Instance-level MCP > Connected clients. Removing local settings does not revoke tokens." };
    }
    const discovery = await inspect(endpoint, network);
    if (record && (record.issuer !== discovery.issuer || record.registrationEndpoint !== discovery.registrationEndpoint)) fail("ISSUER_CHANGED", "The saved issuer or registration endpoint changed. Inspect the deployment before replacing this connection.");
    if (command === "doctor") {
      let callback = "not_configured";
      if (record) {
        try {
          await choosePort(record.callbackPort);
          callback = "available";
        } catch {
          callback = "listening_or_unavailable";
        }
      }
      return {
        ...baseResult,
        status: record?.status === "ready" && entry ? "configured_unverified" : "setup_required",
        registrationStatus: record?.status ?? "absent",
        callback,
        next: "A listening port may belong to Kiro. Only a successful read through Kiro proves authorization and connection.",
        warnings: [consentNote]
      };
    }
    const version = options.kiroVersion ?? await (dependencies.detectKiroVersion ?? detectKiroVersion)();
    requireSupportedKiro(version);
    if (record && record.status !== "ready" && !options.newRegistration) fail("REGISTRATION_UNCERTAIN", "A previous registration did not finish. Consult the instance administrator, then explicitly retry with repair --new-registration if needed.");
    if (record && options.callbackPort !== void 0 && options.callbackPort !== record.callbackPort && command !== "repair") fail("CALLBACK_CHANGE", "Changing an existing callback requires repair --callback-port and fresh authorization.");
    const newRegistration = !record || options.newRegistration || options.callbackPort !== void 0 && options.callbackPort !== record.callbackPort;
    const port = newRegistration ? await choosePort(options.callbackPort ?? record?.callbackPort ?? 0) : record.callbackPort;
    if (options.dryRun) return { ...baseResult, status: "dry_run", action: newRegistration ? "register_and_configure" : "reuse_registration", callbackUri: callbackUri(port), changed: false, warnings: [consentNote] };
    let active = record;
    if (newRegistration) {
      active = {
        endpoint,
        ...discovery,
        serverName,
        configPath: paths.configPath,
        scope: paths.scope,
        kiroVersion: version,
        callbackPort: port,
        status: "registering",
        ...record?.fingerprint ? { fingerprint: record.fingerprint } : {}
      };
      state.connections[key] = active;
      await saveState();
      try {
        active.clientId = await createRegistration(discovery, callbackUri(port), network);
        active.status = "ready";
      } catch (error) {
        active.status = "uncertain";
        await saveState();
        throw error;
      }
      await saveState();
    }
    const desired = connectionConfig(endpoint, active.clientId, port);
    const changed = entry === void 0 || fingerprint(entry) !== fingerprint(desired);
    const nextConfig = changed ? editConfig(configText, serverName, desired) : configText;
    const previousFingerprint = active.fingerprint;
    active.fingerprint = fingerprint(desired);
    if (previousFingerprint && previousFingerprint !== active.fingerprint) active.previousFingerprint = previousFingerprint;
    await saveState();
    await write(paths.configPath, configText, nextConfig);
    delete active.previousFingerprint;
    await saveState();
    return {
      ...baseResult,
      status: "configured_awaiting_authorization",
      changed,
      registration: newRegistration ? "created" : "reused",
      callbackUri: callbackUri(port),
      next: `In Kiro MCP Servers, authenticate ${serverName}, review consent, then ask Kiro for a read-only workflow search.`,
      warnings: [consentNote, ...!options.workspace && paths.scope === "user" ? ["Workspace and agent overrides were not inspected. Run doctor with --workspace for the project you use."] : ["Agent-specific overrides must be checked in Kiro."]]
    };
  };
  if (options.dryRun || command === "doctor") return await action();
  return await withLock(paths.statePath, () => withLock(paths.configPath, action));
}

// src/setup/cli.mjs
async function main(args = process.argv.slice(2)) {
  let json = args.includes("--json");
  try {
    if (Number(process.versions.node.split(".")[0]) < 22) throw new SetupError("NODE_VERSION", "Install Node.js 22 or newer, then rerun setup. No settings were changed.");
    const { values, positionals } = parseArgs({ args, allowPositionals: true, options: {
      url: { type: "string" },
      name: { type: "string" },
      scope: { type: "string" },
      workspace: { type: "string" },
      "callback-port": { type: "string" },
      "kiro-version": { type: "string" },
      "dry-run": { type: "boolean" },
      "new-registration": { type: "boolean" },
      json: { type: "boolean" },
      help: { type: "boolean" }
    } });
    json = Boolean(values.json);
    if (values.help) {
      console.log("Usage: node setup.mjs <configure|doctor|repair|remove> --url <n8n URL>\n\nOptions: --name <name> --scope <user|workspace> --workspace <directory>\n         --callback-port <1024-65535> --kiro-version <installed version>\n         --dry-run --json\nRepair:  --new-registration (explicit retry/replacement) or --callback-port\n\nRequires Node.js 22+ and Kiro IDE 1.1.70. User scope is the default.\nThe helper configures a public client; sign in and approve access in Kiro.");
      return;
    }
    if (positionals.length > 1) throw new SetupError("ARGUMENT", "Supply one command. Use --help for usage.");
    const result = await runSetup({
      command: positionals[0],
      url: values.url,
      name: values.name,
      scope: values.scope,
      workspace: values.workspace,
      callbackPort: values["callback-port"] === void 0 ? void 0 : Number(values["callback-port"]),
      kiroVersion: values["kiro-version"],
      dryRun: values["dry-run"],
      newRegistration: values["new-registration"]
    });
    console.log(json ? JSON.stringify(result) : [
      `${result.serverName}: ${result.status}`,
      `Instance: ${result.endpoint}`,
      `Settings: ${result.configPath}`,
      result.next,
      ...result.warnings ?? []
    ].filter(Boolean).join("\n"));
  } catch (error) {
    const known = error instanceof SetupError;
    const code = known ? error.code : error.code === "CALLBACK_PORT" ? "CALLBACK_PORT" : "SETUP_FAILED";
    const message = known || code === "CALLBACK_PORT" ? error.message : "Setup failed. Check command options, filesystem permissions and file locks. No credentials or server responses are included in this diagnostic.";
    const output = { status: "error", code, message };
    (json ? console.log : console.error)(json ? JSON.stringify(output) : `${code}: ${message}`);
    process.exitCode = 1;
  }
}
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) await main();
export {
  main,
  runSetup
};
