import { build } from 'esbuild';
import { mkdir, readFile, writeFile } from 'node:fs/promises';

const target = 'skills/connect-n8n/scripts/setup.mjs';
const result = await build({
  entryPoints: ['src/setup/cli.mjs'], bundle: true, platform: 'node', format: 'esm',
  target: 'node22', write: false, legalComments: 'inline', charset: 'utf8',
  mainFields: ['module', 'main'],
  banner: { js: '// Generated by npm run build. Edit src/setup/ instead.\n// Includes jsonc-parser (MIT); see THIRD-PARTY-NOTICES.txt.' },
});
const bundle = result.outputFiles[0].text;
const license = (await readFile('node_modules/jsonc-parser/LICENSE.md', 'utf8')).replace(/\r\n/g, '\n');
const notice = 'jsonc-parser 3.3.1\nhttps://github.com/microsoft/node-jsonc-parser\n\n' + license;
if (process.argv.includes('--check')) {
  if (await readFile(target, 'utf8') !== bundle || await readFile('skills/connect-n8n/scripts/THIRD-PARTY-NOTICES.txt', 'utf8') !== notice) {
    throw new Error('Generated helper is stale. Run npm run build.');
  }
} else {
  await mkdir('skills/connect-n8n/scripts', { recursive: true });
  await writeFile(target, bundle);
  await writeFile('skills/connect-n8n/scripts/THIRD-PARTY-NOTICES.txt', notice);
}
